apiVersion: v1
kind: ConfigMap
metadata:
  name: ollive-config
  namespace: ollive
data:
  DJANGO_DEBUG: "true"
  DJANGO_ALLOWED_HOSTS: "*"
  POSTGRES_DB: "ollive_chatbot"
  POSTGRES_USER: "ollive"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  GROQ_MODEL: "llama-3.3-70b-versatile"
  INGEST_URL: "http://localhost:8000/api/ingest/"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_INFERENCE_LOGS_TOPIC: "inference-logs"
  CLICKHOUSE_HOST: "clickhouse"
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_USER: "default"
  CLICKHOUSE_DATABASE: "default"
  CORS_ORIGIN: "http://localhost:5173"
  VITE_API_BASE_URL: "http://localhost:8000/api"
